# -----------------------------------------------------------------------------
# Enable/disable PyLg.
# -----------------------------------------------------------------------------
pylg_enable: True

# -----------------------------------------------------------------------------
# The log file name.
# -----------------------------------------------------------------------------
pylg_file: 'pylg.log'

# -----------------------------------------------------------------------------
# The default value for 'exception_warning'. If True, PyLg will print a warning
# about every exception caught to stderr.
# -----------------------------------------------------------------------------
default_exception_warning: True

# -----------------------------------------------------------------------------
# The default value for 'exception_tb_file'. If True, PyLg will write the
# exception tracebacks to the log file.
# -----------------------------------------------------------------------------
default_exception_tb_file: True

# -----------------------------------------------------------------------------
# The default value for 'exception_tb_file'. If True, PyLg will print the
# exception tracebacks to stderr.
# -----------------------------------------------------------------------------
default_exception_tb_stderr: False

# -----------------------------------------------------------------------------
# The default value for 'exception_exit'. If True, PyLg will force the program
# to exit (and not just raise SystemExit) whenever an exception occurs. This
# will happen even if the exception would be handled at a later point.
# -----------------------------------------------------------------------------
default_exception_exit: False

# -----------------------------------------------------------------------------
# Enable/disable time logging.
# -----------------------------------------------------------------------------
trace_time: True

# -----------------------------------------------------------------------------
# Formatting for the time trace. For a full list of options, see
# https://docs.python.org/2/library/datetime.html#strftime-strptime-behavior.
# -----------------------------------------------------------------------------
time_format: "%Y-%m-%d %H:%M:%S.%f"

# -----------------------------------------------------------------------------
# Enable/disable file name logging.
# -----------------------------------------------------------------------------
trace_filename: True

# -----------------------------------------------------------------------------
# The column width for the file name. If a name is too long, it will be
# truncated.
# -----------------------------------------------------------------------------
filename_column_width: 20

# -----------------------------------------------------------------------------
# Enable/disable the logging of the line number from which the trace call was
# made. For entry and exit messages this logs the line in which the decorator
# is placed (which should be directly above the function itself).
# -----------------------------------------------------------------------------
trace_lineno: True

# -----------------------------------------------------------------------------
# The minimum number of digits to use to print the line number. If the number
# is too long, more digits will be used.
# -----------------------------------------------------------------------------
lineno_width: 4

# -----------------------------------------------------------------------------
# Enable/disable the logging of the function name from which the trace call was
# made. Entry/exit logs refer to the function they enter into and exit from.
# -----------------------------------------------------------------------------
trace_function: True

# -----------------------------------------------------------------------------
# The column width for the function name. If a name is too long, it will be
# truncated.
# -----------------------------------------------------------------------------
function_column_width: 32

# -----------------------------------------------------------------------------
# Enable/disable class name resolution. Function names will be printed with
# their class names.
#
# IMPORTANT: If this setting is enabled, the trace function should ONLY be
# called from within functions that have the @TraceFunction decorator OR
# outside of any function.
# -----------------------------------------------------------------------------
class_name_resolution: False

# -----------------------------------------------------------------------------
# Enable/disable message logging.
# -----------------------------------------------------------------------------
trace_message: True

# -----------------------------------------------------------------------------
# The column width for the message. A width of zero means unlimited.
# -----------------------------------------------------------------------------
message_width: 0

# -----------------------------------------------------------------------------
# If True, PyLg will wrap the message to fit within the column width.
# Otherwise, the message will be truncated.
# -----------------------------------------------------------------------------
message_wrap: True

# -----------------------------------------------------------------------------
# If true, truncated message lines should have the last character replaced with
# '\'. Note that this reduces MESSAGE_WIDTH by 1 for truncated lines which may
# truncate words that would've otherwise appeared in the message.
# -----------------------------------------------------------------------------
message_mark_truncation: True

# -----------------------------------------------------------------------------
# Enable/disable logging of the 'self' function argument.
# -----------------------------------------------------------------------------
trace_self: False

# -----------------------------------------------------------------------------
# If True lists/dictionaries will be collapsed to '[ len=x ]' and '{ len=x }'
# respectively, where x denotes the number of elements in the collection.
# -----------------------------------------------------------------------------
collapse_lists: False
collapse_dicts: False

# -----------------------------------------------------------------------------
# The default setting for 'trace_args'. If True, PyLg will log input
# parameters.
# -----------------------------------------------------------------------------
default_trace_args: True

# -----------------------------------------------------------------------------
# The default setting for 'trace_rv'. If True, PyLg will log return values.
# -----------------------------------------------------------------------------
default_trace_rv: True

# -----------------------------------------------------------------------------
# The default settings for 'trace_rv_type'. If True, PyLg will log return value
# types.
# -----------------------------------------------------------------------------
default_trace_rv_type: False
